safe: false
exclude:
  - README.md
  - Gemfile*
  - docker.sh
  - .gitattributes
  - .gitignore

# Blog specific settings
paginate_path: "posts/page/:num"
paginate: 5

# General settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: [posts]  # this is a slight hack so Jekyll generates the blog posts in /posts


## The application virtual path
baseurl: 
siteversion: 2018.02.10
title: Majorsilence

plugins: [jekyll-paginate, jekyll-redirect-from, jekyll-sitemap]