---
- hosts: winrm
  remote_user: vagrant
  sudo: yes
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_pass: vagrant
    ansible_ssh_port: 5986
    ansible_connection: winrm
  tasks:
    - include: windows-tasks.yml
