# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # please see the online documentation at vagrantup.com.

  
	config.vm.define "website" do |website|
		# Every Vagrant virtual environment requires a box to build off of.
		website.vm.box = "trusty64"
		# website.vm.synced_folder "./sites", "/sites"

		website.vm.provision "ansible" do |ansible|
			ansible.playbook = "./files/website-playbook-test.yml"
			ansible.inventory_path = "./files/hosts"
			ansible.limit = 'all'
			ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
			ansible.verbose = "vvv"
		end

		# The url from where the 'config.vm.box' box will be fetched if it
		# doesn't already exist on the user's system.
		website.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

		# Create a forwarded port mapping which allows access to a specific port
		# within the machine from a port on the host machine. In the example below,
		# accessing "localhost:8080" will access port 80 on the guest machine.
		website.vm.network :forwarded_port, guest: 80, host: 7081
		website.vm.network :forwarded_port, guest: 22, host: 7024
	

		website.vm.network "private_network", ip: "192.167.50.5"

	end


	config.vm.define "windowstestvm" do |windowstestvm|
		# Every Vagrant virtual environment requires a box to build off of.
		windowstestvm.vm.box = "windowstestvm"

		windowstestvm.vm.provision "ansible" do |ansible|
			ansible.playbook = "./files/windows-playbook-test.yml"
			ansible.inventory_path = "./files/hosts"
			ansible.limit = 'all'
			ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
			ansible.verbose = "vvv"
		end
		# The url from where the 'config.vm.box' box will be fetched if it
		# doesn't already exist on the user's system.
		windowstestvm.vm.box_url = "The link to your windows box"

		windowstestvm.vm.network "private_network", ip: "192.167.50.5"
		windowstestvm.vm.guest = :windows
		windowstestvm.vm.communicator = :winrm
		windowstestvm.winrm.guest_port = 5985
		# Ensure that all networks are set to private, required on windows 7
		windowstestvm.winrm.set_work_network = true
		# Port forward WinRM and RDP
		windowstestvm.vm.network :forwarded_port, guest: 3389, host: 9094
		windowstestvm.vm.network :forwarded_port, guest: 80, host: 8088
		windowstestvm.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
		windowstestvm.vm.network :forwarded_port, guest: 5986, host: 5986, id: "winrm2", auto_correct: true
	end



end
