name: .NET

on:
  push:
    branches: [ "gh-pages" ]
  pull_request:
    branches: [ "gh-pages" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup md2gemini 
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          md2gemini
    - run: md2gemini _posts/* --write --frontmatter --strip-html --dir gemini-output/
    
