name: gemini

on:
  push:
    branches: [ "gh-pages" ]
  pull_request:
    branches: [ "gh-pages" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup md2gemini 
      uses: BSFishy/pip-action@v1
      with:
        packages: |
          md2gemini
    - name: Convert to gemini capsule 
      run:  |
        rm -rf $GITHUB_WORKSPACE/gemini-output
        mkdir -p $GITHUB_WORKSPACE/gemini-output
        md2gemini _posts/* --write --frontmatter --strip-html --dir $GITHUB_WORKSPACE/gemini-output/
    
